/*
 * SatelliteDNA.org
 * 
 * 2017
 */
package org.satellitedna.ui;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import javax.swing.JOptionPane;
import org.satellitedna.utils.PropertyManager;

/**
 *
 * @author clopez
 */
public class CompilerOptions extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private GetOptionDialog fileDialog;
    private final PropertyManager propertyManager;
    private final ArrayList<NamePair> items = new ArrayList<>();
    private boolean status;

    public boolean isStatus() {
        return status;
    }

    /**
     * Creates new form CompilerOptions
     *
     * @param propertyManager
     */
    public CompilerOptions(PropertyManager propertyManager) {
        initComponents();

        fileDialog = new GetOptionDialog(this, true);

        status = false;
        this.propertyManager = propertyManager;
        fileDialog = new GetOptionDialog(null, true);

        Enumeration its = propertyManager.keys();
        while (its.hasMoreElements()) {

            String key = (String) its.nextElement();
            String value = propertyManager.getProperty(key);

            if (CompilerFlags.COMPILER_BASE.name().equalsIgnoreCase(key)) {
                jTextFieldCompilerBase.setText(value);
                NamePair p = new NamePair(CompilerFlags.COMPILER_BASE.name(), value);
                this.items.add(p);

            }
            if (CompilerFlags.INCPATH.name().equalsIgnoreCase(key)) {
                jTextFieldINCPATH.setText(value);

            }
            if (CompilerFlags.CC.name().equalsIgnoreCase(key)) {
                jTextFieldCC.setText(value);

            }
            if (CompilerFlags.CCX.name().equalsIgnoreCase(key)) {
                jTextFieldCCX.setText(value);
            }
            if (CompilerFlags.LIBS.name().equalsIgnoreCase(key)) {
                jTextFieldLIBS.setText(value);
            }
            if (CompilerFlags.CFLAGS.name().equalsIgnoreCase(key)) {
                jTextFieldCFLAGS.setText(value);
            }
            if (CompilerFlags.LFLAGS.name().equalsIgnoreCase(key)) {
                jTextFieldLFLAGS.setText(value);
            }

        }

    }

    private String showFileDialog(String oldValue, boolean dirsOnly) {

        FileDialogN n = new FileDialogN();
        return n.getFile(null,oldValue, dirsOnly,false);

    }

    private String getOptionDialog(String label, String oldValue, boolean dirsOnly) {
        GetOptionDialog g = new GetOptionDialog(this, true);

        g.initialize(label, oldValue, dirsOnly);
        g.setVisible(true);
        if (g.wasCancelled() == false) {
            return g.getSelected();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLFLAGS = new javax.swing.JTextField();
        jButtonLFLAGS = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCompilerBase = new javax.swing.JTextField();
        jButtonCompilerBase = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCC = new javax.swing.JTextField();
        jButtonCC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCCX = new javax.swing.JTextField();
        jButtonCCX = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCFLAGS = new javax.swing.JTextField();
        jButtonCFLAGS = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldINCPATH = new javax.swing.JTextField();
        jButtonINCPATH = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLIBS = new javax.swing.JTextField();
        jButtonLIBS = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compiler Options");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("LFLAGS");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));
        jPanel3.add(jTextFieldLFLAGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, -1));

        jButtonLFLAGS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/development-2.png"))); // NOI18N
        jButtonLFLAGS.setText("Change");
        jButtonLFLAGS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLFLAGSMouseClicked(evt);
            }
        });
        jPanel3.add(jButtonLFLAGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CompilerBase");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        jTextFieldCompilerBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCompilerBaseActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCompilerBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, -1));

        jButtonCompilerBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/development-2.png"))); // NOI18N
        jButtonCompilerBase.setText("Change");
        jButtonCompilerBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCompilerBaseMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCompilerBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("CC");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));
        jPanel2.add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 430, -1));

        jButtonCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/development-2.png"))); // NOI18N
        jButtonCC.setText("Change");
        jButtonCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCCMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("CCX");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));
        jPanel4.add(jTextFieldCCX, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, -1));

        jButtonCCX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/development-2.png"))); // NOI18N
        jButtonCCX.setText("Change");
        jButtonCCX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCCXMouseClicked(evt);
            }
        });
        jPanel4.add(jButtonCCX, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("CFLAGS");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        jTextFieldCFLAGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCFLAGSActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldCFLAGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, -1));

        jButtonCFLAGS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/development-2.png"))); // NOI18N
        jButtonCFLAGS.setText("Change");
        jButtonCFLAGS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCFLAGSMouseClicked(evt);
            }
        });
        jPanel5.add(jButtonCFLAGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("INCPATH");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));
        jPanel6.add(jTextFieldINCPATH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, -1));

        jButtonINCPATH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/development-2.png"))); // NOI18N
        jButtonINCPATH.setText("Change");
        jButtonINCPATH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonINCPATHMouseClicked(evt);
            }
        });
        jPanel6.add(jButtonINCPATH, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("LIBS");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));
        jPanel7.add(jTextFieldLIBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, -1));

        jButtonLIBS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/development-2.png"))); // NOI18N
        jButtonLIBS.setText("Change");
        jButtonLIBS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLIBSMouseClicked(evt);
            }
        });
        jPanel7.add(jButtonLIBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/dialog-ok-2.png"))); // NOI18N
        jButtonOK.setText("Accept");
        jButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKMouseClicked(evt);
            }
        });

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/satellitedna/ui/dialog-cancel-4.png"))); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jButtonOK)
                .addGap(45, 45, 45)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonCancel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCompilerBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompilerBaseMouseClicked
        // TODO add your handling code here:

        String file = showFileDialog(propertyManager.getProperty(CompilerFlags.COMPILER_BASE.name()), true);

        if (file != null) {
            jTextFieldCompilerBase.setText(fileDialog.getSelected());
        }


    }//GEN-LAST:event_jButtonCompilerBaseMouseClicked

    private void jButtonCCXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCCXMouseClicked
        // TODO add your handling code here:

        String file = showFileDialog(propertyManager.getProperty(CompilerFlags.CCX.name()), false);
        if (file != null) {
            this.jTextFieldCCX.setText(fileDialog.getSelected());
        }
    }//GEN-LAST:event_jButtonCCXMouseClicked

    private void jButtonCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCCMouseClicked
        // TODO add your handling code here:
        String file = showFileDialog(propertyManager.getProperty(CompilerFlags.CC.name()), false);

        if (file != null) {
            this.jTextFieldCC.setText(fileDialog.getSelected());
        }
    }//GEN-LAST:event_jButtonCCMouseClicked

    private void jButtonLFLAGSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLFLAGSMouseClicked
        // TODO add your handling code here:

        String option = getOptionDialog(CompilerFlags.LFLAGS.name(), propertyManager.getProperty(CompilerFlags.LFLAGS.name()), false);

        if (option != null) {
            this.jTextFieldLFLAGS.setText(option);
        }
    }//GEN-LAST:event_jButtonLFLAGSMouseClicked

    private void jButtonCFLAGSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCFLAGSMouseClicked
        // TODO add your handling code here:

        String option = getOptionDialog(CompilerFlags.CFLAGS.name(), propertyManager.getProperty(CompilerFlags.CFLAGS.name()), false);

        if (option != null) {
            this.jTextFieldCFLAGS.setText(option);
        }
    }//GEN-LAST:event_jButtonCFLAGSMouseClicked

    private void jButtonINCPATHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonINCPATHMouseClicked
        // TODO add your handling code here:
        String option = getOptionDialog(CompilerFlags.INCPATH.name(), propertyManager.getProperty(CompilerFlags.INCPATH.name()), false);

        if (option != null) {
            this.jTextFieldINCPATH.setText(option);
        }
    }//GEN-LAST:event_jButtonINCPATHMouseClicked

    private void jButtonLIBSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLIBSMouseClicked
        // TODO add your handling code here:

        String option = getOptionDialog(CompilerFlags.LIBS.name(), propertyManager.getProperty(CompilerFlags.LIBS.name()), false);

        if (option != null) {
            this.jTextFieldLIBS.setText(option);
        }
    }//GEN-LAST:event_jButtonLIBSMouseClicked

    private void jButtonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKMouseClicked
        // TODO add your handling code here:

        NamePair p = new NamePair(CompilerFlags.INCPATH.name(), jTextFieldINCPATH.getText());
        this.items.add(p);

        if (jTextFieldCC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "error  CC is invalid");
            return;
        }
        if (jTextFieldCCX.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "error  CCX is invalid");
            return;
        }
        if (jTextFieldCompilerBase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "error  Compiler base is invalid");
            return;
        }

        p = new NamePair(CompilerFlags.CC.name(), jTextFieldCC.getText());
        this.items.add(p);

        p = new NamePair(CompilerFlags.CCX.name(), jTextFieldCCX.getText());
        this.items.add(p);
        p = new NamePair(CompilerFlags.CFLAGS.name(), jTextFieldCFLAGS.getText());
        this.items.add(p);
        p = new NamePair(CompilerFlags.LFLAGS.name(), jTextFieldLFLAGS.getText());
        this.items.add(p);

        p = new NamePair(CompilerFlags.LIBS.name(), jTextFieldLIBS.getText());
        this.items.add(p);
        p = new NamePair(CompilerFlags.COMPILER_BASE.name(), jTextFieldCompilerBase.getText());
        this.items.add(p);

        Iterator<NamePair> its = this.items.iterator();
        while (its.hasNext()) {
            p = its.next();
            propertyManager.setProperty(p.getName(), p.getValue());

        }
        this.status = true;
        this.setVisible(false);

        propertyManager.saveToClassLoader();
    }//GEN-LAST:event_jButtonOKMouseClicked

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        // TODO add your handling code here:
        this.status = false;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void jTextFieldCFLAGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCFLAGSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCFLAGSActionPerformed

    private void jTextFieldCompilerBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCompilerBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompilerBaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCC;
    private javax.swing.JButton jButtonCCX;
    private javax.swing.JButton jButtonCFLAGS;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCompilerBase;
    private javax.swing.JButton jButtonINCPATH;
    private javax.swing.JButton jButtonLFLAGS;
    private javax.swing.JButton jButtonLIBS;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldCCX;
    private javax.swing.JTextField jTextFieldCFLAGS;
    private javax.swing.JTextField jTextFieldCompilerBase;
    private javax.swing.JTextField jTextFieldINCPATH;
    private javax.swing.JTextField jTextFieldLFLAGS;
    private javax.swing.JTextField jTextFieldLIBS;
    // End of variables declaration//GEN-END:variables
}
